public class MainWindow extends javax.swing.JFrame {

	/**
	 * Creates new form YahtzeeWindow
	 */
	public MainWindow() {
		initComponents();
	}

	private static final int BUTTON_SIZE = 45;
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		analyseRollsButton.setText("Look at my rolls");

		rollDice.setText("1. Roll the dice");

		jLabel2.setText("2. Select an entry:");

		lockDie1Button.setIcon(new javax.swing.ImageIcon("res/dice_empty.png")); // NOI18N

		lockDie2Button.setIcon(new javax.swing.ImageIcon("res/dice_empty.png")); // NOI18N

		lockDie3Button.setIcon(new javax.swing.ImageIcon("res/dice_empty.png")); // NOI18N

		lockDie4Button.setIcon(new javax.swing.ImageIcon("res/dice_empty.png")); // NOI18N

		lockDie5Button.setIcon(new javax.swing.ImageIcon("res/dice_empty.png")); // NOI18N

		selectOnesButton.setText("-");

		jLabel12.setText("ones:");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel12)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectOnesButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel4Layout.setVerticalGroup(
				jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectOnesButton)
						.addComponent(jLabel12))
				);

		selectTwosButton.setText("-");

		jLabel14.setText("twos:");

		javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
		jPanel6.setLayout(jPanel6Layout);
		jPanel6Layout.setHorizontalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel14)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectTwosButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel6Layout.setVerticalGroup(
				jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectTwosButton)
						.addComponent(jLabel14))
				);

		selectThreesButton.setText("-");

		jLabel15.setText("threes:");

		javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
		jPanel7.setLayout(jPanel7Layout);
		jPanel7Layout.setHorizontalGroup(
				jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel15)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectThreesButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel7Layout.setVerticalGroup(
				jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectThreesButton)
						.addComponent(jLabel15))
				);

		selectFoursButton.setText("-");

		jLabel16.setText("fours:");

		javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
		jPanel8.setLayout(jPanel8Layout);
		jPanel8Layout.setHorizontalGroup(
				jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel16)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectFoursButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel8Layout.setVerticalGroup(
				jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectFoursButton)
						.addComponent(jLabel16))
				);

		selectFivesButton.setText("-");

		jLabel17.setText("fives:");

		javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
		jPanel9.setLayout(jPanel9Layout);
		jPanel9Layout.setHorizontalGroup(
				jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel17)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectFivesButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel9Layout.setVerticalGroup(
				jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectFivesButton)
						.addComponent(jLabel17))
				);

		selectSixesButton.setText("-");

		jLabel18.setText("sixes:");

		javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
		jPanel10.setLayout(jPanel10Layout);
		jPanel10Layout.setHorizontalGroup(
				jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel18)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectSixesButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel10Layout.setVerticalGroup(
				jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectSixesButton)
						.addComponent(jLabel18))
				);

		jLabel19.setText("sum:");

		partialSumLabel.setText("0");

		javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
		jPanel11.setLayout(jPanel11Layout);
		jPanel11Layout.setHorizontalGroup(
				jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel19)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
						.addComponent(partialSumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				);
		jPanel11Layout.setVerticalGroup(
				jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel19)
						.addComponent(partialSumLabel))
				);

		jLabel20.setText("bonus:");

		bonusLabel.setText("0");

		javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
		jPanel12.setLayout(jPanel12Layout);
		jPanel12Layout.setHorizontalGroup(
				jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel20)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
						.addComponent(bonusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				);
		jPanel12Layout.setVerticalGroup(
				jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel20)
						.addComponent(bonusLabel))
				);

		selectOnePairButton.setText("-");

		jLabel21.setText("1 pair:");

		javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
		jPanel13.setLayout(jPanel13Layout);
		jPanel13Layout.setHorizontalGroup(
				jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel21)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectOnePairButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel13Layout.setVerticalGroup(
				jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectOnePairButton)
						.addComponent(jLabel21))
				);

		selectTwoPairButton.setText("-");

		jLabel22.setText("2 pair:");

		javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
		jPanel14.setLayout(jPanel14Layout);
		jPanel14Layout.setHorizontalGroup(
				jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel22)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectTwoPairButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel14Layout.setVerticalGroup(
				jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectTwoPairButton)
						.addComponent(jLabel22))
				);

		selectThreeOAKButton.setText("-");

		jLabel23.setText("3 of a kind:");

		javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
		jPanel15.setLayout(jPanel15Layout);
		jPanel15Layout.setHorizontalGroup(
				jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel23)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectThreeOAKButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel15Layout.setVerticalGroup(
				jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectThreeOAKButton)
						.addComponent(jLabel23))
				);

		SelectFourOAKButton.setText("-");

		jLabel24.setText("4 of a kind:");

		javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
		jPanel16.setLayout(jPanel16Layout);
		jPanel16Layout.setHorizontalGroup(
				jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel24)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(SelectFourOAKButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel16Layout.setVerticalGroup(
				jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(SelectFourOAKButton)
						.addComponent(jLabel24))
				);

		selectSmallStraightButton.setText("-");

		jLabel25.setText("small straight:");

		javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
		jPanel17.setLayout(jPanel17Layout);
		jPanel17Layout.setHorizontalGroup(
				jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel25)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectSmallStraightButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel17Layout.setVerticalGroup(
				jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectSmallStraightButton)
						.addComponent(jLabel25))
				);

		selectLargeStraightButton.setText("-");

		jLabel26.setText("large straight:");

		javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
		jPanel18.setLayout(jPanel18Layout);
		jPanel18Layout.setHorizontalGroup(
				jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel26)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
						.addComponent(selectLargeStraightButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel18Layout.setVerticalGroup(
				jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectLargeStraightButton)
						.addComponent(jLabel26))
				);

		selectFullHouseButton.setText("-");

		jLabel27.setText("full house:");

		javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
		jPanel19.setLayout(jPanel19Layout);
		jPanel19Layout.setHorizontalGroup(
				jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel27)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
						.addComponent(selectFullHouseButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel19Layout.setVerticalGroup(
				jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectFullHouseButton)
						.addComponent(jLabel27))
				);

		selectChanceButton.setText("-");

		jLabel28.setText("chance:");

		javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
		jPanel20.setLayout(jPanel20Layout);
		jPanel20Layout.setHorizontalGroup(
				jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel20Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel28)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectChanceButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel20Layout.setVerticalGroup(
				jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectChanceButton)
						.addComponent(jLabel28))
				);

		selectYahtzeeButton.setText("-");

		jLabel29.setText("yahtzee:");

		javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
		jPanel21.setLayout(jPanel21Layout);
		jPanel21Layout.setHorizontalGroup(
				jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel29)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(selectYahtzeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, BUTTON_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
				);
		jPanel21Layout.setVerticalGroup(
				jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(selectYahtzeeButton)
						.addComponent(jLabel29))
				);

		jLabel30.setText("total sum:");

		totalSumLabel.setText("0");

		javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
		jPanel22.setLayout(jPanel22Layout);
		jPanel22Layout.setHorizontalGroup(
				jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jLabel30)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(totalSumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap())
				);
		jPanel22Layout.setVerticalGroup(
				jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
						.addComponent(jLabel30)
						.addComponent(totalSumLabel))
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel2)
								.addGroup(layout.createSequentialGroup()
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(rollDice, javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(analyseRollsButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
												.addGap(18, 18, 18)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(layout.createSequentialGroup()
																.addComponent(lockDie1Button)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(lockDie2Button)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(lockDie3Button)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(lockDie4Button)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(lockDie5Button))
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																		.addComponent(jPanel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(jPanel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(jPanel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(jPanel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																		.addComponent(jPanel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
																		.addGroup(layout.createSequentialGroup()
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
																						.addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																						.addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
																						.addGap(18, 18, 18)
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
																								.addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																								.addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																								.addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
																								.addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
																								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addContainerGap()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
								.addGroup(layout.createSequentialGroup()
										.addComponent(rollDice)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(analyseRollsButton))
										.addComponent(lockDie1Button)
										.addComponent(lockDie2Button)
										.addComponent(lockDie3Button)
										.addComponent(lockDie4Button)
										.addComponent(lockDie5Button))
										.addGap(18, 18, 18)
										.addComponent(jLabel2)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
												.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
														.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																				.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																								.addGroup(layout.createSequentialGroup()
																										.addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addGroup(layout.createSequentialGroup()
																												.addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
																												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																												.addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																												.addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		pack();
	}// </editor-fold>                        




	// Variables declaration - do not modify                     
	public final javax.swing.JButton SelectFourOAKButton = new javax.swing.JButton();
	public final javax.swing.JButton analyseRollsButton = new javax.swing.JButton();
	public final javax.swing.JLabel bonusLabel = new javax.swing.JLabel();
	public final javax.swing.JButton jButton12 = new javax.swing.JButton();
	public final javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel13 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel14 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel15 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel16 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel17 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel18 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel19 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel20 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel21 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel22 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel23 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel24 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel25 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel26 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel27 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel28 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel29 = new javax.swing.JLabel();
	public final javax.swing.JLabel jLabel30 = new javax.swing.JLabel();
	public final javax.swing.JPanel jPanel10 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel11 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel12 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel13 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel14 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel15 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel16 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel17 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel18 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel19 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel20 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel21 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel22 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel5 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel6 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel7 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel8 = new javax.swing.JPanel();
	public final javax.swing.JPanel jPanel9 = new javax.swing.JPanel();
	public final javax.swing.JToggleButton lockDie1Button = new javax.swing.JToggleButton();
	public final javax.swing.JToggleButton lockDie2Button = new javax.swing.JToggleButton();
	public final javax.swing.JToggleButton lockDie3Button = new javax.swing.JToggleButton();
	public final javax.swing.JToggleButton lockDie4Button = new javax.swing.JToggleButton();
	public final javax.swing.JToggleButton lockDie5Button = new javax.swing.JToggleButton();
	public final javax.swing.JLabel partialSumLabel = new javax.swing.JLabel();
	public final javax.swing.JLabel rollDice = new javax.swing.JLabel();
	public final javax.swing.JButton selectChanceButton = new javax.swing.JButton();
	public final javax.swing.JButton selectFivesButton = new javax.swing.JButton();
	public final javax.swing.JButton selectFoursButton = new javax.swing.JButton();
	public final javax.swing.JButton selectFullHouseButton = new javax.swing.JButton();
	public final javax.swing.JButton selectLargeStraightButton = new javax.swing.JButton();
	public final javax.swing.JButton selectOnePairButton = new javax.swing.JButton();
	public final javax.swing.JButton selectOnesButton = new javax.swing.JButton();
	public final javax.swing.JButton selectSixesButton = new javax.swing.JButton();
	public final javax.swing.JButton selectSmallStraightButton = new javax.swing.JButton();
	public final javax.swing.JButton selectThreeOAKButton = new javax.swing.JButton();
	public final javax.swing.JButton selectThreesButton = new javax.swing.JButton();
	public final javax.swing.JButton selectTwoPairButton = new javax.swing.JButton();
	public final javax.swing.JButton selectTwosButton = new javax.swing.JButton();
	public final javax.swing.JButton selectYahtzeeButton = new javax.swing.JButton();
	public final javax.swing.JLabel totalSumLabel = new javax.swing.JLabel();
	// End of variables declaration                   
}
