/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package xfish.xraySimulator;

import javax.swing.DefaultListModel;

import xfish.xraySimulator.data.GeometryFile;

/**
 *
 * @author Bart
 */
public class SimulatorSetupWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public SimulatorSetupWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        simulateButton.setText("Simulate");

        geometryFileArea.setDividerLocation(200);

        geometrySourceLabel.setText("Geometry sources");

        geometrySourceList.setModel(new DefaultListModel());
        geometrySourceScrollPane.setViewportView(geometrySourceList);

        addGeometrySourceButton.setText("Add..");

        removeSelectedSourceButton.setText("Remove selected");

        javax.swing.GroupLayout geometryListPaneLayout = new javax.swing.GroupLayout(geometryListPane);
        geometryListPane.setLayout(geometryListPaneLayout);
        geometryListPaneLayout.setHorizontalGroup(
            geometryListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geometryListPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(geometryListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(geometryListPaneLayout.createSequentialGroup()
                        .addGroup(geometryListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(geometrySourceLabel)
                            .addComponent(geometrySourceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(geometryListPaneLayout.createSequentialGroup()
                        .addComponent(addGeometrySourceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(removeSelectedSourceButton)))
                .addContainerGap())
        );
        geometryListPaneLayout.setVerticalGroup(
            geometryListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geometryListPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geometrySourceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geometrySourceScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(geometryListPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGeometrySourceButton)
                    .addComponent(removeSelectedSourceButton))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        geometryFileArea.setLeftComponent(geometryListPane);

        geometryDensityLabel.setText("Relative density");

        javax.swing.GroupLayout geometryPropertiesPaneLayout = new javax.swing.GroupLayout(geometryPropertiesPane);
        geometryPropertiesPane.setLayout(geometryPropertiesPaneLayout);
        geometryPropertiesPaneLayout.setHorizontalGroup(
            geometryPropertiesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geometryPropertiesPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(geometryPropertiesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(geometryDensityLabel)
                    .addComponent(geometryDensity, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        geometryPropertiesPaneLayout.setVerticalGroup(
            geometryPropertiesPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(geometryPropertiesPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(geometryDensityLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geometryDensity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        geometryFileArea.setRightComponent(geometryPropertiesPane);

        emitterPositionLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        emitterPositionLabel.setText("Emitter position");

        rotationLabel.setText("Fish rotation:");

        emitterXLabel.setText("x:");

        emitterYLabel.setText("y:");

        emitterZLabel.setText("z:");

        detector1positionHeader.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        detector1positionHeader.setText("Left detector position:");

        leftDetectorLabel.setText("x:");

        rightDetectorHeader.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rightDetectorHeader.setText("Right detector position:");

        rightDetectorX.setText("x:");

        imageWidthLabel.setText("Image width:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(geometryFileArea)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rotationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rotationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simulateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emitterPositionLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(emitterXLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emitterX))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(emitterYLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emitterY))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(emitterZLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(emitterZ)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(detector1positionHeader)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(leftDetectorLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(leftDetector, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rightDetectorX)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rightDetector, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(rightDetectorHeader)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(imageWidthLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(imageWidth)
                                .addGap(265, 265, 265)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(geometryFileArea, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emitterPositionLabel)
                    .addComponent(detector1positionHeader)
                    .addComponent(rightDetectorHeader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emitterXLabel)
                    .addComponent(emitterX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leftDetectorLabel)
                    .addComponent(leftDetector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightDetectorX)
                    .addComponent(rightDetector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emitterYLabel)
                    .addComponent(emitterY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emitterZLabel)
                    .addComponent(emitterZ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imageWidthLabel)
                    .addComponent(imageWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(simulateButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rotationLabel)
                        .addComponent(rotationSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public final javax.swing.JButton addGeometrySourceButton = new javax.swing.JButton();
    public final javax.swing.JLabel detector1positionHeader = new javax.swing.JLabel();
    public final javax.swing.JLabel emitterPositionLabel = new javax.swing.JLabel();
    public final javax.swing.JSpinner emitterX = new javax.swing.JSpinner();
    public final javax.swing.JLabel emitterXLabel = new javax.swing.JLabel();
    public final javax.swing.JSpinner emitterY = new javax.swing.JSpinner();
    public final javax.swing.JLabel emitterYLabel = new javax.swing.JLabel();
    public final javax.swing.JSpinner emitterZ = new javax.swing.JSpinner();
    public final javax.swing.JLabel emitterZLabel = new javax.swing.JLabel();
    public final javax.swing.JSpinner geometryDensity = new javax.swing.JSpinner();
    public final javax.swing.JLabel geometryDensityLabel = new javax.swing.JLabel();
    public final javax.swing.JSplitPane geometryFileArea = new javax.swing.JSplitPane();
    public final javax.swing.JPanel geometryListPane = new javax.swing.JPanel();
    public final javax.swing.JPanel geometryPropertiesPane = new javax.swing.JPanel();
    public final javax.swing.JLabel geometrySourceLabel = new javax.swing.JLabel();
    public final javax.swing.JList<GeometryFile> geometrySourceList = new javax.swing.JList<GeometryFile>();
    public final javax.swing.JScrollPane geometrySourceScrollPane = new javax.swing.JScrollPane();
    public final javax.swing.JSpinner imageWidth = new javax.swing.JSpinner();
    public final javax.swing.JLabel imageWidthLabel = new javax.swing.JLabel();
    public final javax.swing.JSpinner leftDetector = new javax.swing.JSpinner();
    public final javax.swing.JLabel leftDetectorLabel = new javax.swing.JLabel();
    public final javax.swing.JButton removeSelectedSourceButton = new javax.swing.JButton();
    public final javax.swing.JSpinner rightDetector = new javax.swing.JSpinner();
    public final javax.swing.JLabel rightDetectorHeader = new javax.swing.JLabel();
    public final javax.swing.JLabel rightDetectorX = new javax.swing.JLabel();
    public final javax.swing.JLabel rotationLabel = new javax.swing.JLabel();
    public final javax.swing.JSpinner rotationSpinner = new javax.swing.JSpinner();
    public final javax.swing.JButton simulateButton = new javax.swing.JButton();
    // End of variables declaration//GEN-END:variables
}
